trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'cloudorders-azure-connection'
  webAppName: 'cloudorders-api-escasan'
  keyVaultName: 'cloudorders-kv-escasan'
  sqlConnectionSecretName: 'CloudOrdersSqlConnection'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.0.x'

    - script: dotnet restore
      displayName: 'Restore'

    - script: dotnet build --no-restore --configuration $(buildConfiguration)
      displayName: 'Build'

    - script: dotnet test --no-build --configuration $(buildConfiguration)
      displayName: 'Test'

    - script: dotnet publish src/CloudOrders.Api --no-build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/app
      displayName: 'Publish API'

    - script: dotnet tool install --global dotnet-ef --version "10.0.10"
      displayName: 'Install EF Core tools'

    - script: dotnet restore --runtime linux-x64
      displayName: 'Restore solution for linux-x64'

    - script: dotnet ef migrations bundle --project src/CloudOrders.Infrastructure --startup-project src/CloudOrders.Api --configuration $(buildConfiguration) --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)/migrations/efbundle
      displayName: 'Build migration bundle'

    - publish: $(Build.ArtifactStagingDirectory)/app
      artifact: drop

    - publish: $(Build.ArtifactStagingDirectory)/migrations
      artifact: migrations

- stage: Migrate
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: MigrateAzureSql
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(azureSubscription)
              KeyVaultName: $(keyVaultName)
              SecretsFilter: $(sqlConnectionSecretName)

          - script: chmod +x "$(Pipeline.Workspace)/migrations/efbundle" && "$(Pipeline.Workspace)/migrations/efbundle" --connection "$DB_CONNECTION_STRING"
            displayName: 'Apply Azure SQL migrations'
            env:
              DB_CONNECTION_STRING: $($(sqlConnectionSecretName))

- stage: Deploy
  dependsOn: Migrate
  condition: succeeded()
  jobs:
  - deployment: DeployToAzure
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webAppLinux'
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop'