<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Inventory</AssemblyName>
    <RootNamespace>Inventory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Inventory.Tests\**" />
    <Compile Remove="Inventory.IntegrationTests\**" />
    <Content Remove="Inventory.Tests\**" />
    <Content Remove="Inventory.IntegrationTests\**" />
    <EmbeddedResource Remove="Inventory.Tests\**" />
    <EmbeddedResource Remove="Inventory.IntegrationTests\**" />
    <None Remove="Inventory.Tests\**" />
    <None Remove="Inventory.IntegrationTests\**" />
  </ItemGroup>
</Project>
